### ISSUE TITLE
Define required exception fields during class definition using __init_subclass__.

### ISSUE THREAD

**Issue by gtdrakeley** [dusktreader/py-buzz#71]
It would be useful to be able to define required fields beyond "message" on custom exceptions without overriding `__init__` by using [`__init_subclass__`](https://docs.python.org/3/reference/datamodel.html#object.__init_subclass__).

```python
import buzz

class ExampleError(buzz.Buzz, required_fields=("field1", "field2")):
    pass
```

Also see [PEP-0487](https://www.python.org/dev/peps/pep-0487/) for the history of `__init_subclass__`.

**Comment by dusktreader** [comment]
Resolved by PR #73
