### ISSUE TITLE
improve usage documentation

### ISSUE THREAD

**Issue by jamesbeedy** [dusktreader/py-buzz#75]
The usage documentation is a little light....
<img width="741" alt="Screen Shot 2022-03-19 at 5 20 13 PM" src="https://user-images.githubusercontent.com/5590546/159142826-c4c698c3-1006-4c6c-a58f-e5ce0486059c.png">

It would be helpful if you could provide some thorough descriptions that describe what the convenience methods are, how to use them and what purpose they serve, basically the 5 Ws.

**Comment by jamesbeedy** [comment]
I see the usage is described in the "features" doc https://py-buzz.readthedocs.io/en/latest/features.html

**Comment by dusktreader** [comment]
Added a link to the "Features" page on this page. Released with 3.1.0.
